import Head from "next/head"
import { useEffect, useState } from "react"
import { Footer } from "./footer"
import { Header } from "./header"


export function Layout({children, title}) {
    const [ dark, setDark ] = useState(typeof window !=='undefined' ? JSON.parse(localStorage.getItem("darkMode")) : false )

    const handleDark = () => {
        setDark(() => !dark);
        localStorage.setItem("darkMode", JSON.stringify(!dark))
        //console.log("DarkMode")
    }

    useEffect(() => {
       setDark(() => JSON.parse(localStorage.getItem("darkMode")))
    }, [ dark ])

    //console.log(dark)

   
        return(
            <>
                <Head>
                    <title>{ title }</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
                    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css"></link>
                </Head>
                
                <div style={{ backgroundColor: dark ? "black" : "white"}}>
                    <Header dark={dark} darkMode={handleDark}/>
                    <main className="w-100">
                        { children }
                    </main>
                    <Footer />
                </div>
            </>
        )
}